### ISSUE TITLE
Allow subscribing to notifications of new versions

### ISSUE THREAD

**Issue by onishiweb** [Financial-Times/origami-registry#2]
Unsure exactly how this would work.  Ideas include:

- When a new version is detected, and it's on Github, fetch a list of all the stargazers and email them (https://github.com/neoziro/stargazer).
- Allow subscribing directly on the registry, add a table of subscribers and maintain that locally.

Also unsure how we'd send the email - ideally through the new email service.

(Migrated from Jira issues)

**Comment by onishiweb** [comment]
Unsure if this is still worth pursuing? 

Option 1 basing it on `stargazers` wouldn't be overly useful as most components have little or no stargazers at all, only one with many is `o-grid`.

Option 2 I'm not sure if anyone would be interested in beyond the notifications in Slack? 

Should we just close this @alicebartlett @rowanmanning @JakeChampion ?

**Comment by alicebartlett** [comment]
This seems like something that would be useful in theory but I don't think in reality that that many people would use it.
Let's close this for now and if it comes up as something people want we can re-open.

**Comment by onishiweb** [comment]
👍
