### ISSUE TITLE
Add: graphite stats for /packages/ endpoint

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-registry#58]
If we add stats for this endpoint, we can figure out which components are being requested the most from the registry. This will help us figure out which components we can deprecate.

**Comment by onishiweb** [comment]
We already have these being tracked in Graphite, just need to work out the best way to show these metrics, there's a lot of components...

**Comment by JakeChampion** [comment]
Do you know which metric in graphite will be able to answer the question - "Which components are being installed the most?"

**Comment by onishiweb** [comment]
`origami.registry.prod.serve.bower.*` has counts for each module.
