### ISSUE TITLE
Custom elements do not render correctly in demos

### ISSUE THREAD

**Issue by antoligy** [Financial-Times/origami-registry#7]
Hey, admittedly I'm not too sure if this is the right place for this issue!

Essentially when rendering a demo, the source displayed in the registry seems to break after the first dash (afaik required by web components).  An example of this can be [seen here](http://registry.origami.ft.com/components/o-share) showing an `<o />` tag [whereas the demo](https://github.com/Financial-Times/o-share/blob/master/demos/src/webcomponent.mustache) uses `<o-share />`.

**Comment by onishiweb** [comment]
Hi @antoligy thanks for reporting the issue, turns out it was the HTML parser we were using and updating to the latest version fixed it. Will be deployed soon.

**Comment by antoligy** [comment]
Nice one, thanks @onishiweb!
