### ISSUE TITLE
Registry referencing origami-build.ft.com

### ISSUE THREAD

**Issue by antoligy** [Financial-Times/origami-registry#91]
Hey,

Not entirely sure if this is an issue or not, but figured it wouldn't hurt to ask.  I'm getting links on the Registry pointing to origami-build.ft.com (SERVER.BUILD_HOST afaict?).  Should this reference the new URL? https://www.ft.com/__origami/service/image/v2

(I only noticed as I've just run into what looks like a OCSP issue on macOS which is preventing me from accessing origami-build)

**Comment by onishiweb** [comment]
I'll double check with @rowanmanning whether we're ok to switch to the new build service URL, if so I'll get that updated soon.

**Comment by JakeChampion** [comment]
@onishiweb We're all good to switch 👍

**Comment by onishiweb** [comment]
Ok, we're updated to the new build service URL now, all tested and live.

Thanks @antoligy

**Comment by antoligy** [comment]
Woohoo, cheers 😄
